### ISSUE TITLE
Unable to record event with remote Sentry server (Raven::Error - Connection reset by peer - SSL_connect)

### ISSUE THREAD

**Issue by igorkasyanchuk** [getsentry/sentry-ruby#1073]
**Describe the bug**
Can't submit event to the Sentry.

**To Reproduce**
Loading production environment (Rails 6.0.3.2)
2.6.3 :001 > begin
2.6.3 :002?>     1 / 0
2.6.3 :003?>   rescue ZeroDivisionError => exception
2.6.3 :004?>     Raven.capture_exception(exception)
2.6.3 :005?>   end
Sending event df69675da79848559bd286f80c8765df to Sentry
Raven HTTP Transport connecting to https://sentry.io
Unable to record event with remote Sentry server (Raven::Error - Connection reset by peer - SSL_connect):
/home/deployer/.rvm/gems/ruby-2.6.3/gems/sentry-raven-3.0.0/lib/raven/transports/http.rb:34:in `rescue in send_event'
/home/deployer/.rvm/gems/ruby-2.6.3/gems/sentry-raven-3.0.0/lib/raven/transports/http.rb:16:in `send_event'
/home/deployer/.rvm/gems/ruby-2.6.3/gems/sentry-raven-3.0.0/lib/raven/client.rb:44:in `send_event'
/home/deployer/.rvm/gems/ruby-2.6.3/gems/sentry-raven-3.0.0/lib/raven/instance.rb:81:in `send_event'
/home/deployer/.rvm/gems/ruby-2.6.3/gems/sentry-raven-3.0.0/lib/raven/instance.rb:126:in `capture_type'
/home/deployer/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `capture_exception'
(irb):4:in `rescue in irb_binding'
(irb):1:in `irb_binding'
/home/deployer/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/irb/workspace.rb:85:in `eval'
/home/deployer/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/irb/workspace.rb:85:in `evaluate'
/home/deployer/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/irb/context.rb:385:in `evaluate'
Failed to submit event: ZeroDivisionError: divided by 0

**Expected behavior**

Before it was sending events.

**Actual behavior**

**Environment**
 - Ruby Version: 2.6.3
 - SDK Version: 3.0.0
 - Integration Versions (if any):
  - Rails 6.0, Sidekiq 5

**Comment by igorkasyanchuk** [comment]
Sorry, just realized that our DevOps disabled network from the VPS
