### ISSUE TITLE
Redis::CommandError Sidekiq errorERR max number of clients reached

### ISSUE THREAD

**Issue by joshm1204** [getsentry/sentry-ruby#1141]
**Describe the bug**

 I have an app that has zero traffic on Heroku. The only item that I believe is using Redis is Sentry and HireFire. I had Hirefire for a while, and no issues, but recently added Sentry and now, even when my app is idle for a week (no traffic), I get a bunch of Redis "connection time outs" and "max connection to Redis" errors. I believe Sentry is doing something to use up all the redis connections.  I have 30 available connections, and my sidekiq.yml is set for 17.

**To Reproduce**
## Puma.rb
```

workers Integer(ENV['WEB_CONCURRENCY'] || 2)
max_threads_count = Integer(ENV['RAILS_MAX_THREADS'] || 5)
min_threads_count =  Integer(ENV['RAILS_MIN_THREADS'] || max_threads_count)
threads min_threads_count, max_threads_count
preload_app!
port        ENV['PORT']     || 3000
# Specifies the `environment` that Puma will run in.
environment ENV['RACK_ENV'] || 'development'
# Specifies the `pidfile` that Puma will use.
pidfile ENV.fetch("PIDFILE") { "tmp/pids/server.pid" }
before_fork do
  puts "Puma master process about to fork. Closing existing Active record connections."
  ActiveRecord::Base.connection.disconnect!
end
on_worker_boot do
  # Worker specific setup for Rails 4.1+
  # See: https://devcenter.heroku.com/articles/deploying-rails-applications-with-the-puma-web-server#on-worker-boot
  ActiveRecord::Base.establish_connection
end
# Allow puma to be restarted by `rails restart` command.
plugin :tmp_restart
```
## SideKiq.yml

```
:verbose: true
:concurrency: 10
:timeout: 25

:queues:
  - critical
  - default
  - mailers

production:
  :verbose: false
  :concurrency: 17
staging:
  :concurrency: 10
```

## sentryjob.rb

```
class SentryJob < ApplicationJob
  queue_as :default

  def perform(event)
    Raven.send_event(event)
  end
end
```
##  sentry-raven.rb

```
Raven.configure do |config|
  config.dsn = ENV['SENTRY_DSN']
  config.async = lambda { |event| SentryJob.perform_later(event)}
end
```
## Hirefire.rb

```
HireFire::Resource.configure do |config|
  config.log_queue_metrics = true
  config.dyno(:worker) do
    HireFire::Macro::Sidekiq.queue
  end
end
```

## Example Error

```
IO::EINPROGRESSWaitWritable: Operation now in progress - connect(2) would block
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/socket.rb:1214:in `__connect_nonblock'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/socket.rb:1214:in `connect_nonblock'
  from redis (4.2.2) lib/redis/connection/ruby.rb:161:in `connect_addrinfo'
  from redis (4.2.2) lib/redis/connection/ruby.rb:199:in `block in connect'
  from redis (4.2.2) lib/redis/connection/ruby.rb:197:in `each'
  from redis (4.2.2) lib/redis/connection/ruby.rb:197:in `each_with_index'
  from redis (4.2.2) lib/redis/connection/ruby.rb:197:in `connect'
  from redis (4.2.2) lib/redis/connection/ruby.rb:299:in `connect'
  from redis (4.2.2) lib/redis/client.rb:349:in `establish_connection'
  from redis (4.2.2) lib/redis/client.rb:107:in `block in connect'
  from redis (4.2.2) lib/redis/client.rb:308:in `with_reconnect'
  from redis (4.2.2) lib/redis/client.rb:106:in `connect'
  from redis (4.2.2) lib/redis/client.rb:381:in `ensure_connected'
  from redis (4.2.2) lib/redis/client.rb:233:in `block in process'
  from redis (4.2.2) lib/redis/client.rb:320:in `logging'
  from redis (4.2.2) lib/redis/client.rb:232:in `process'
  from redis (4.2.2) lib/redis/client.rb:126:in `call'
  from redis (4.2.2) lib/redis/client.rb:221:in `block in call_with_timeout'
  from redis (4.2.2) lib/redis/client.rb:295:in `with_socket_timeout'
  from redis (4.2.2) lib/redis/client.rb:220:in `call_with_timeout'
  from redis (4.2.2) lib/redis.rb:1224:in `block in _bpop'
  from redis (4.2.2) lib/redis.rb:69:in `block in synchronize'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  from redis (4.2.2) lib/redis.rb:69:in `synchronize'
  from redis (4.2.2) lib/redis.rb:1221:in `_bpop'
  from redis (4.2.2) lib/redis.rb:1266:in `brpop'
  from sidekiq (6.1.2) lib/sidekiq/fetch.rb:39:in `block in retrieve_work'
  from sidekiq (6.1.2) lib/sidekiq.rb:98:in `block in redis'
  from connection_pool (2.2.3) lib/connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool (2.2.3) lib/connection_pool.rb:62:in `handle_interrupt'
  from connection_pool (2.2.3) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.2.3) lib/connection_pool.rb:59:in `handle_interrupt'
  from connection_pool (2.2.3) lib/connection_pool.rb:59:in `with'
  from sidekiq (6.1.2) lib/sidekiq.rb:95:in `redis'
  from sidekiq (6.1.2) lib/sidekiq/fetch.rb:39:in `retrieve_work'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:83:in `get_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:95:in `fetch'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:77:in `process_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:15:in `watchdog'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:24:in `block in safe_thread'

Redis::TimeoutError: Redis::TimeoutError
  from redis (4.2.2) lib/redis/connection/ruby.rb:163:in `rescue in connect_addrinfo'
  from redis (4.2.2) lib/redis/connection/ruby.rb:160:in `connect_addrinfo'
  from redis (4.2.2) lib/redis/connection/ruby.rb:199:in `block in connect'
  from redis (4.2.2) lib/redis/connection/ruby.rb:197:in `each'
  from redis (4.2.2) lib/redis/connection/ruby.rb:197:in `each_with_index'
  from redis (4.2.2) lib/redis/connection/ruby.rb:197:in `connect'
  from redis (4.2.2) lib/redis/connection/ruby.rb:299:in `connect'
  from redis (4.2.2) lib/redis/client.rb:349:in `establish_connection'
  from redis (4.2.2) lib/redis/client.rb:107:in `block in connect'
  from redis (4.2.2) lib/redis/client.rb:308:in `with_reconnect'
  from redis (4.2.2) lib/redis/client.rb:106:in `connect'
  from redis (4.2.2) lib/redis/client.rb:381:in `ensure_connected'
  from redis (4.2.2) lib/redis/client.rb:233:in `block in process'
  from redis (4.2.2) lib/redis/client.rb:320:in `logging'
  from redis (4.2.2) lib/redis/client.rb:232:in `process'
  from redis (4.2.2) lib/redis/client.rb:126:in `call'
  from redis (4.2.2) lib/redis/client.rb:221:in `block in call_with_timeout'
  from redis (4.2.2) lib/redis/client.rb:295:in `with_socket_timeout'
  from redis (4.2.2) lib/redis/client.rb:220:in `call_with_timeout'
  from redis (4.2.2) lib/redis.rb:1224:in `block in _bpop'
  from redis (4.2.2) lib/redis.rb:69:in `block in synchronize'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  from redis (4.2.2) lib/redis.rb:69:in `synchronize'
  from redis (4.2.2) lib/redis.rb:1221:in `_bpop'
  from redis (4.2.2) lib/redis.rb:1266:in `brpop'
  from sidekiq (6.1.2) lib/sidekiq/fetch.rb:39:in `block in retrieve_work'
  from sidekiq (6.1.2) lib/sidekiq.rb:98:in `block in redis'
  from connection_pool (2.2.3) lib/connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool (2.2.3) lib/connection_pool.rb:62:in `handle_interrupt'
  from connection_pool (2.2.3) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.2.3) lib/connection_pool.rb:59:in `handle_interrupt'
  from connection_pool (2.2.3) lib/connection_pool.rb:59:in `with'
  from sidekiq (6.1.2) lib/sidekiq.rb:95:in `redis'
  from sidekiq (6.1.2) lib/sidekiq/fetch.rb:39:in `retrieve_work'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:83:in `get_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:95:in `fetch'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:77:in `process_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:15:in `watchdog'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:24:in `block in safe_thread'

Redis::CannotConnectError: Error connecting to Redis on 
 (Redis::TimeoutError)
  from redis (4.2.2) lib/redis/client.rb:362:in `rescue in establish_connection'
  from redis (4.2.2) lib/redis/client.rb:343:in `establish_connection'
  from redis (4.2.2) lib/redis/client.rb:107:in `block in connect'
  from redis (4.2.2) lib/redis/client.rb:308:in `with_reconnect'
  from redis (4.2.2) lib/redis/client.rb:106:in `connect'
  from redis (4.2.2) lib/redis/client.rb:381:in `ensure_connected'
  from redis (4.2.2) lib/redis/client.rb:233:in `block in process'
  from redis (4.2.2) lib/redis/client.rb:320:in `logging'
  from redis (4.2.2) lib/redis/client.rb:232:in `process'
  from redis (4.2.2) lib/redis/client.rb:126:in `call'
  from redis (4.2.2) lib/redis/client.rb:221:in `block in call_with_timeout'
  from redis (4.2.2) lib/redis/client.rb:295:in `with_socket_timeout'
  from redis (4.2.2) lib/redis/client.rb:220:in `call_with_timeout'
  from redis (4.2.2) lib/redis.rb:1224:in `block in _bpop'
  from redis (4.2.2) lib/redis.rb:69:in `block in synchronize'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `synchronize'
  from vendor/ruby-2.7.1/lib/ruby/2.7.0/monitor.rb:202:in `mon_synchronize'
  from redis (4.2.2) lib/redis.rb:69:in `synchronize'
  from redis (4.2.2) lib/redis.rb:1221:in `_bpop'
  from redis (4.2.2) lib/redis.rb:1266:in `brpop'
  from sidekiq (6.1.2) lib/sidekiq/fetch.rb:39:in `block in retrieve_work'
  from sidekiq (6.1.2) lib/sidekiq.rb:98:in `block in redis'
  from connection_pool (2.2.3) lib/connection_pool.rb:63:in `block (2 levels) in with'
  from connection_pool (2.2.3) lib/connection_pool.rb:62:in `handle_interrupt'
  from connection_pool (2.2.3) lib/connection_pool.rb:62:in `block in with'
  from connection_pool (2.2.3) lib/connection_pool.rb:59:in `handle_interrupt'
  from connection_pool (2.2.3) lib/connection_pool.rb:59:in `with'
  from sidekiq (6.1.2) lib/sidekiq.rb:95:in `redis'
  from sidekiq (6.1.2) lib/sidekiq/fetch.rb:39:in `retrieve_work'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:83:in `get_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:95:in `fetch'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:77:in `process_one'
  from sidekiq (6.1.2) lib/sidekiq/processor.rb:68:in `run'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:15:in `watchdog'
  from sidekiq (6.1.2) lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Expected behavior**
I expect Sentry to not cause SideKiq to use all my Redis connections.

**Actual behavior**
All my redis connections are being used up.

**Environment**
 - Ruby Version: 2.7.1
 - SDK Version: 
Sentry-Raven Version: 3.1.1
 - Integration Versions (if any):
Redis 4.2.2, Rails 6.0.3.3, SideKiq 6.1.2

**Comment by st0012** [comment]
this doesn't look like the SDK's issue, because the SDK itself doesn't make any connection to the Redis. 

one possible cause could be the `async` config. because you use `ActiveJob` (with `sidekiq`) to report exceptions in the background, every time there's an exception it'll enqueue a job via `ActiveJob`. so if you get many exceptions in a short period of time, it could cause some issues on the backgrounding library or/and the Redis.

I recommend you to comment out the `config.async` line and see if the connection issue goes away. if that does, it means the problem is probably what I mentioned above, which is on the job enqueuing but not the SDK.
