### ISSUE TITLE
NoMethodError (undefined method `configuration' for nil:NilClass)

### ISSUE THREAD

**Issue by cxspxr** [getsentry/sentry-ruby#1203]
**Describe the bug**
I am trying to migrate from sentry-raven to sentry-ruby in an existing project. With sentry-raven everything works well.

**To Reproduce**
Not sure though, with a fresh project it works fine. Of course I am not expecting a full solution to this problem, just maybe some thoughts that may help me to figure out what's wrong.

**Expected behavior**
Rails should not error.

**Actual behavior**
It errors in some places on some controller actions with this (though Sentry is not being used in those actions): 

```
/home/casper/.rvm/gems/ruby-2.6.6/gems/sentry-rails-4.1.3/lib/sentry/rails/rescued_exception_interceptor.rb:12: warning: #<Class:Sentry>#configuration at /home/casper/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/forwardable.rb:158 forwarding to private method NilClass#configuration
  
NoMethodError (undefined method `configuration' for nil:NilClass):
  
/home/casper/.rvm/rubies/ruby-2.6.6/lib/ruby/2.6.0/forwardable.rb:228:in `configuration'
sentry-rails (4.1.3) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `rescue in call'
sentry-rails (4.1.3) lib/sentry/rails/rescued_exception_interceptor.rb:8:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
remotipart (1.4.4) lib/remotipart/middleware.rb:32:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
warden (1.2.9) lib/warden/manager.rb:34:in `catch'
warden (1.2.9) lib/warden/manager.rb:34:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activerecord (6.0.3.4) lib/active_record/migration.rb:567:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-contrib (2.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.7.2) lib/meta_request/middlewares/headers.rb:16:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
web-console (4.1.0) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.1.0) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `catch'
web-console (4.1.0) lib/web_console/middleware.rb:17:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
sprockets-rails (3.2.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
skylight-core (4.3.2) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rails_autoscale_agent (0.10.1) lib/rails_autoscale_agent/middleware.rb:27:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-livereload (0.3.17) lib/rack/livereload.rb:23:in `_call'
rack-livereload (0.3.17) lib/rack/livereload.rb:14:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
sentry-ruby (4.1.3) lib/sentry/rack/capture_exceptions.rb:9:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
rack-mini-profiler (2.3.0) lib/mini_profiler/profiler.rb:373:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
webpacker (5.2.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
newrelic_rpm (6.14.0) lib/new_relic/agent/instrumentation/middleware_tracing.rb:101:in `call'
puma (5.1.1) lib/puma/configuration.rb:246:in `call'
puma (5.1.1) lib/puma/request.rb:76:in `block in handle_request'
puma (5.1.1) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
puma (5.1.1) lib/puma/request.rb:75:in `handle_request'
puma (5.1.1) lib/puma/server.rb:431:in `process_client'
puma (5.1.1) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
```

**Environment**
 - Ruby Version: 2.6.6p146
 - SDK Version: 4.1.3
 - Integration Versions (if any):
  - Rails 6.0.3, Sidekiq 5.2

**Sentry Config**

```ruby
if ENV['SENTRY_DSN']
  Sentry.init do |config|
    config.dsn = ENV['SENTRY_DSN']
    config.traces_sampler = lambda do |context|
      true
    end
    config.send_default_pii = true
    config.environment = ENV['SERVER_ENV'] || 'development'
    config.excluded_exceptions += %w[ActionController::RoutingError ActiveRecord::RecordNotFound]
  end
end
```

**Comment by cxspxr** [comment]
Could it be that sentry-raven previously did the `excluded from capture: DSN not set` ? Because seems like that sentry-ruby fails at the places where sentry-raven said that some info was `excluded from capture: DSN not set`

**Comment by cxspxr** [comment]
Okay now, it was https://github.com/flyerhzm/bullet/ 
It was trying to use raven classes instead of sentry-ruby

**Comment by st0012** [comment]
@cxspxr thanks for reporting. although the SDK itself is not the root cause of the issue, I still think there's a room for improvement. so I just added https://github.com/getsentry/sentry-ruby/pull/1204 for it.
