### ISSUE TITLE
NoMethodError: undefined method `log_arguments=' for Sentry::SendEventJob:Class

### ISSUE THREAD

**Issue by durcak** [getsentry/sentry-ruby#1270]
**Describe the bug**
Hello, I'm trying to upgrade sentry-ruby/rails/sidekiq from version 4.1.7  to 4.2.0, but I am getting this error after call `rails zeitwerk:check`:

```
$ rails zeitwerk:check --trace
** Invoke zeitwerk:check (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute zeitwerk:check
Hold on, I am eager loading the application.
rails aborted!
NoMethodError: undefined method `log_arguments=' for Sentry::SendEventJob:Class
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-rails-4.2.0/app/jobs/sentry/send_event_job.rb:12:in `<class:SendEventJob>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-rails-4.2.0/app/jobs/sentry/send_event_job.rb:11:in `<module:Sentry>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sentry-rails-4.2.0/app/jobs/sentry/send_event_job.rb:3:in `<main>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:26:in `require'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `const_get'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:409:in `block (2 levels) in eager_load'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:733:in `block in ls'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `foreach'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:725:in `ls'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:404:in `block in eager_load'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `synchronize'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:393:in `eager_load'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `each'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/loader.rb:508:in `eager_load_all'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/tasks/zeitwerk.rake:11:in `block in <main>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/tasks/zeitwerk.rake:47:in `block (2 levels) in <main>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/command.rb:52:in `invoke'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.1/lib/rails/commands.rb:18:in `<main>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/td/workspace/progrocery-backend/bin/rails:10:in `<top (required)>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/Users/td/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
/Users/td/workspace/progrocery-backend/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => zeitwerk:check
```

**To Reproduce**
 - Run `bundle exec rails zeitwek:check`

**Expected behavior**
 - Pass zeitwerk check.

**Actual behavior**
 - Fails.

**Environment**
 - Ruby Version: 2.7.2
 - SDK Version: sentry-ruby 4.2.0
 - Integration Versions (if any):
  - Rails 6.1.1
  - Sidekiq 6.1.3
  - sentry-rails 4.2.0
  - sentry-sidekiq 4.2.0

**Sentry Config**

This is not necessary but could be helpful.

```ruby
Sentry.init do |config|
  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, _hint|
    request_data = event.request&.data&.is_a?(String) ? JSON.parse(event.request.data) : event.request&.data
    event.request.data = filter.filter(request_data) unless request_data.nil?
    event
  end
  config.send_default_pii = false
  config.environment = sentry_environment
  config.excluded_exceptions += SENTRY_IGNORED_EXCEPTIONS.map(&:to_s)
  config.breadcrumbs_logger = [:active_support_logger]
  config.rails.report_rescued_exceptions = false
end
```

**Comment by st0012** [comment]
it's weird that I can't reproduce this with the example app:

```
$ be rails -v
Rails 6.1.1
$ bundle exec rails zeitwerk:check
Hold on, I am eager loading the application.
All is good!
```

the `log_arguments` is a new method added in Rails `6.1` so it should just work 🤔 

can you:

1. try it again with spring stopped
2. run `bundle exec rails runner "puts Sentry::SendEventJob.log_arguments"`

**Comment by durcak** [comment]
This is result:
```
$ be rails -v
Rails 6.1.1

$ be rails zeitwerk:check
Hold on, I am eager loading the application.
rails aborted!
NoMethodError: undefined method `log_arguments=' for Sentry::SendEventJob:Class
/Users/td/workspace/pb/bin/rails:10:in `<top (required)>'
/Users/td/workspace/pb/bin/spring:15:in `require'
/Users/td/workspace/pb/bin/spring:15:in `<top (required)>'
Tasks: TOP => zeitwerk:check
(See full trace by running task with --trace)

$ spring stop
Spring stopped.

$ be rails runner "puts Sentry::SendEventJob.log_arguments"
Running via Spring preloader in process 89781
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `log_arguments=' for Sentry::SendEventJob:Class
```

**Comment by st0012** [comment]
thanks, can you try this then? 

```
$ bundle exec rails runner "puts ActiveJob.version; puts Sentry::SendEventJob.ancestors"
```

**Comment by durcak** [comment]
```
$ bundle exec rails runner "puts ActiveJob.version; puts Sentry::SendEventJob.ancestors"
Running via Spring preloader in process 90206
6.1.1
Please specify a valid ruby command or the path of a script to run.
Run 'rails runner -h' for help.

undefined method `log_arguments=' for Sentry::SendEventJob:Class
```

**Comment by st0012** [comment]
looks like it's completely un-initializeable.
can you downgrade the SDK to `4.1.x` and try this again?

```
$ bundle exec rails runner "puts ActiveJob.version; puts ActiveJob::Base.log_arguments = false"
```

**Comment by durcak** [comment]
with `gem 'sentry-ruby', '~> 4.1.6'`

```
& bundle exec rails runner "puts ActiveJob.version; ActiveJob::Base.log_arguments = false"
Running via Spring preloader in process 90698
6.1.1
```

**Comment by durcak** [comment]
Hmm, I have got it, check this code https://github.com/getsentry/sentry-ruby/blob/6146708524ba16da00808ca359ec0085b9c83fb7/sentry-rails/app/jobs/sentry/send_event_job.rb#L5 
and in my application I have 
```
class ApplicationJob
  include Sidekiq::Worker
  include Sidekiq::Status::Worker
end
```

**Comment by durcak** [comment]
With 
```
  class SendEventJob < parent_job
    # self.log_arguments = false if ::Rails.version.to_f >= 6.1
    # discard_on ActiveJob::DeserializationError # this will prevent infinite loop when there's an issue deserializing SentryJob

    def perform(event, hint = {})
      Sentry.send_event(event, hint)
    end
  end
```
its initializeable
```
$ bundle exec rails runner "puts ActiveJob.version; puts Sentry::SendEventJob.ancestors"
Running via Spring preloader in process 93358
6.1.1
Sentry::SendEventJob
ApplicationJob
#<Module:0x00007fc568a76f68>
#<Module:0x00007fc54ea33278>
#<Module:0x00007fc54ea332a0>
ActionDispatch::Routing::UrlFor
ActionDispatch::Routing::PolymorphicRoutes
Sidekiq::Status::Worker
Sidekiq::Status::Storage
Sidekiq::Worker::Options
Sidekiq::Worker
Sidekiq::Batch::Extension::Worker
ActiveSupport::Dependencies::ZeitwerkIntegration::RequireDependency
ActiveSupport::ForkTracker::CoreExtPrivate
ActiveSupport::ForkTracker::CoreExt
ActiveSupport::ToJsonWithActiveSupportEncoder
Object
V8::Conversion::Object
RequireAll
PP::ObjectMixin
JSON::Ext::Generator::GeneratorMethods::Object
ActiveSupport::Dependencies::Loadable
ActiveSupport::Tryable
Kernel
BasicObject

```

**Comment by st0012** [comment]
@durcak thanks for the information, I will fix it in the next patch release 👍
