### ISSUE TITLE
Method missing discard_on

### ISSUE THREAD

**Issue by newmana** [getsentry/sentry-ruby#1277]
**Describe the bug**
Cannot start Sidekiq job and returns a stack trace.

```
2021-02-08T22:51:39.016Z pid=19331 tid=go4twcym7 WARN: NoMethodError: undefined method `discard_on' for Sentry::SendEventJob:Class
2021-02-08T22:51:39.016Z pid=19331 tid=go4twcym7 WARN: /var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/sentry-rails-4.2.0/app/jobs/sentry/send_event_job.rb:13:in `<class:SendEventJob>'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/sentry-rails-4.2.0/app/jobs/sentry/send_event_job.rb:11:in `<module:Sentry>'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/sentry-rails-4.2.0/app/jobs/sentry/send_event_job.rb:3:in `<top (required)>'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `block in require'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:293:in `require'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:380:in `block in require_or_load'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:37:in `load_interlock'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:358:in `require_or_load'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:336:in `depend_on'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/dependencies.rb:252:in `require_dependency'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:476:in `block (2 levels) in eager_load!'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:475:in `each'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:475:in `block in eager_load!'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:473:in `each'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:473:in `eager_load!'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:354:in `eager_load!'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:59:in `each'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/application/finisher.rb:59:in `block in <module:Finisher>'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `instance_exec'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:30:in `run'
/var/deploy/canceraid/web_head/shared/bundle/ruby/2.5.0/gems/railties-5.0.7.2/lib/rails/initializable.rb:55:in `block in run_initializers'
```

**To Reproduce**
Using Rails 5.0.x,
Start a Sidekiq job.

**Expected behavior**
Able to start job (works with previous Rails library 4.1.6).

**Actual behavior**
Crashes.

**Environment**
 - Ruby Version: 2.5.8
 - SDK Version: 4.1.6
 - Integration Versions (if any): Sidekiq 6.1.3, Rails 5.0.7.2

**Raven Config**

N/A.

**Comment by st0012** [comment]
thanks for reporting this. I think it could be the same issue mentioned in #1270, do you have `ApplicationJob` define in your application?

**Comment by newmana** [comment]
No I don't. Here's my ./config/application.rb

```require File.expand_path('../boot', __FILE__)

require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "action_controller/railtie"
require "action_mailer/railtie"
require "action_view/railtie"
require "sprockets/railtie"
# require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module XXXXXXXXXXX
  class Application < Rails::Application
    # Use the responders controller from the responders gem
    config.app_generators.scaffold_controller :responders_controller

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de
    config.eager_load_paths << Rails.root.join('lib')

    # Make the asset pipeline play nice with Bower
    config.assets.paths << Rails.root.join('vendor', 'assets', 'components')

    config.autoload_paths << Rails.root.join('app', 'queries', 'concerns')
    config.autoload_paths << Rails.root.join('app', 'serializers', 'concerns')
  end
end
```

**Comment by st0012** [comment]
ah ok I know the reason now: the `discard_on` method was added in Rails 5.1. I will add a check for it.
