### ISSUE TITLE
Multiple Unreported Events 

### ISSUE THREAD

**Issue by abhinavmsra** [getsentry/sentry-ruby#1383]
**Describe the bug**
While most errors are still reported to Sentry, some bugs are not tracked. For untracked errors, following is the stacktrace

```
FATAL -- 
NoMethodError (undefined method `shopname' for nil:NilClass):  
app/models/transaction.rb:132:in `assign_shopname'
app/controllers/api/v1/transactions_controller.rb:69:in `create'
ERROR -- sentry: Event sending failed: undefined method `new' for NilClass:Class
ERROR -- sentry: Unreported Event: NoMethodError: undefined method `shopname' for nil:NilClass

---- 

NoMethodError (undefined method `classify' for nil:NilClass):
app/policies/transaction_policy.rb:20:in `resolve'
app/controllers/api/v1/transactions_controller.rb:30:in `block (2 levels) in index'
app/controllers/api/v1/transactions_controller.rb:17:in `index'
ERROR -- sentry: Event sending failed: undefined method `new' for NilClass:Class
ERROR -- sentry: Unreported Event: NoMethodError: undefined method `classify' for nil:NilClass
```

**To Reproduce**
I could not figure out how to reproduce specific untracked errors.

**Expected behavior**
ALL errors to be reported 

**Actual behavior**
Some errors are missed

**Environment**
 - Ruby Version: 3
 - SDK Version:
 ```
sentry-rails (4.3.3)
      railties (>= 5.0)
      sentry-ruby-core (~> 4.3.0)
    sentry-ruby (4.3.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      faraday (>= 1.0)
      sentry-ruby-core (= 4.3.1)
    sentry-ruby-core (4.3.1)
      concurrent-ruby
      faraday
    sentry-sidekiq (4.3.0)
      sentry-ruby-core (~> 4.3.0)
 ```
 - Integration Versions (if any):
  - Rails 6.1.3.1, Sidekiq 6.2.0

```ruby
Sentry.init do |config|
    filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)

    config.dsn = Rails.application.credentials.sentry_dsn
    config.breadcrumbs_logger = [:active_support_logger]
    config.traces_sample_rate = 0.2

    config.before_send = ->(event, _hint) do
      request = event.request
      if request
        request.data = filter.filter(request.data)
      end
      event
    end
  end
```

**Comment by st0012** [comment]
thanks for reporting this. can you add this to your `config/initializers/sentry.rb`?

```ruby
module Sentry
  class Client
    def send_event(event, hint = nil)
      event_type = event.is_a?(Event) ? event.type : event["type"]

      if event_type != TransactionEvent::TYPE && configuration.before_send
        event = configuration.before_send.call(event, hint)

        if event.nil?
          logger.info(LOGGER_PROGNAME) { "Discarded event because before_send returned nil" }
          return
        end
      end

      transport.send_event(event)

      event
    rescue => e
      loggable_event_type = (event_type || "event").capitalize
      logger.error(LOGGER_PROGNAME) { "#{loggable_event_type} sending failed: #{e.message}" }
      logger.error(LOGGER_PROGNAME) { e.backtrace } # this is the new line that will print the backtrace of SDK error
      logger.error(LOGGER_PROGNAME) { "Unreported #{loggable_event_type}: #{Event.get_log_message(event.to_hash)}" }
      raise
    end
  end
end
```

it will print the backtrace of SDK's error.

**Comment by abhinavmsra** [comment]
sure, will do & follow back when I have proper logs

**Comment by abhinavmsra** [comment]
Here's the stacktrace

```
FATAL -- : NoMethodError (undefined method `map' for nil:NilClass):
app/queries/transaction_monthly_query.rb:23:in `timestamps'
#
===============
ERROR -- sentry: Event sending failed: undefined method `new' for NilClass:Class
ERROR -- sentry: [
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/parameter_filter.rb:99:in `call'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/activesupport-6.1.3.1/lib/active_support/parameter_filter.rb:44:in `filter'",
"[ROOT_PATH]/releases/20210405063949/config/initializers/sentry.rb:42:in `block (2 levels) in <main>'",
"[ROOT_PATH]/releases/20210405063949/config/initializers/sentry.rb:9:in `send_event'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.3.1/lib/sentry/client.rb:97:in `block in dispatch_background_event'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/sentry-rails-4.3.3/lib/sentry/rails/background_worker.rb:7:in `block (2 levels) in perform'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/sentry-rails-4.3.3/lib/sentry/rails/background_worker.rb:6:in `block in perform'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'",
"[ROOT_PATH]/shared/bundle/ruby/3.0.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'"]
ERROR -- sentry: Unreported Event: NoMethodError: undefined method `map' for nil:NilClass
```

This makes me think parameter filtering is the root cause

```ruby
Sentry.init do |config|
  filter = ActiveSupport::ParameterFilter.new(Rails.application.config.filter_parameters)
  config.before_send = lambda do |event, hint|
    request = event.request

      if request
        request.data = filter.filter(request.data)
      end

      event
  end
end
```

**Comment by st0012** [comment]
@abhinavmsra I guess it's because `request.data` is `nil` in those events. checking its presence before passing it to the filter should work. 

however, I also recommend another cleaner approach for event filtering now:

```ruby
  config.before_send = lambda do |event, _hint|
    filter.filter(event.to_hash)
  end
```

with the above approach, it'll sanitize the entire event payload (like the old SDK). you can also be sure that the same issue would never happen because `event.to_hash` doesn't return `nil` 🙂

**Comment by st0012** [comment]
@abhinavmsra does the above change fix the issue?

**Comment by abhinavmsra** [comment]
> @abhinavmsra does the above change fix the issue?

Seems to be working, havent noticed any issues after this fix. Thanks
