### ISSUE TITLE
core_ext/object/deep_dup Segmentation fault

### ISSUE THREAD

**Issue by NaturalHokke** [getsentry/sentry-ruby#1485]
**Describe the bug**
```
/app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/core_ext/object/deep_dup.rb:32: [BUG] Segmentation fault at 0x000000000007f590

- ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

- -- Control frame information -----------------------------------------------
- c:0022 p:---- s:0153 e:000152 CFUNC :map
- c:0021 p:0006 s:0149 e:000148 METHOD /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/core_ext/object/deep_dup.rb:32
- c:0020 p:0013 s:0145 e:000143 METHOD /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/breadcrumb_buffer.rb:44
- c:0019 p:0013 s:0139 e:000137 METHOD /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/scope.rb:56
- c:0018 p:0018 s:0133 e:000132 METHOD /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/hub.rb:36
- c:0017 p:0025 s:0127 e:000124 METHOD /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry-ruby.rb:130
- c:0016 p:0032 s:0121 e:000120 METHOD /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/rack/capture_exceptions.rb:12
- c:0015 p:0014 s:0116 e:000115 METHOD /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14
- c:0014 p:0018 s:0108 e:000107 METHOD /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24
- c:0013 p:0007 s:0103 e:000102 METHOD /app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110
- c:0012 p:0028 s:0091 e:000090 METHOD /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/ssl.rb:77
- c:0011 p:0014 s:0085 e:000084 METHOD /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:92
- c:0010 p:0052 s:0079 e:000078 METHOD /app/vendor/bundle/ruby/3.0.0/gems/scout_apm-4.1.1/lib/scout_apm/instruments/middleware_summary.rb:58
- c:0009 p:0016 s:0072 e:000071 METHOD /app/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539
- c:0008 p:0028 s:0066 e:000065 METHOD /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/configuration.rb:249
- c:0007 p:0008 s:0061 e:000060 BLOCK /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:77
- c:0006 p:0023 s:0058 e:000057 METHOD /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338
- c:0005 p:0274 s:0053 e:000052 METHOD /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:76
- c:0004 p:0128 s:0032 e:000031 METHOD /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/server.rb:438 [FINISH]
- c:0003 p:---- s:0020 e:000019 IFUNC
- c:0002 p:0094 s:0017 e:000014 BLOCK /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145 [FINISH]
- c:0001 p:---- s:0003 e:000002 (none) [FINISH]


- -- Ruby level backtrace information ----------------------------------------
- /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:145:in `block in spawn_thread'
- /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/server.rb:438:in `process_client'
- /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:76:in `handle_request'
- /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/thread_pool.rb:338:in `with_force_shutdown'
- /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/request.rb:77:in `block in handle_request'
- /app/vendor/bundle/ruby/3.0.0/gems/puma-5.3.2/lib/puma/configuration.rb:249:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/railties-6.1.3.2/lib/rails/engine.rb:539:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/scout_apm-4.1.1/lib/scout_apm/instruments/middleware_summary.rb:58:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/host_authorization.rb:92:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/ssl.rb:77:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/static.rb:24:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/rack/capture_exceptions.rb:12:in `call'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry-ruby.rb:130:in `clone_hub_to_current_thread'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/hub.rb:36:in `clone'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/scope.rb:56:in `dup'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/breadcrumb_buffer.rb:44:in `dup'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/core_ext/object/deep_dup.rb:32:in `deep_dup'
- /app/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-core-4.5.1/lib/sentry/core_ext/object/deep_dup.rb:32:in `map'
```

**To Reproduce**

**Expected behavior**

**Actual behavior**

**Environment**
 - Ruby Version: 3.0.1
 - SDK Version: 4.5.1
 - Integration Versions (if any):
  - Rails 6.1.3.2
  - Sidekiq 6.2.1

**Raven Config**

This is not necessary but could be helpful.

```ruby
Sentry.init  do |config|
  config.breadcrumbs_logger = %i[active_support_logger http_logger]
  config.traces_sample_rate = 0.0
end
```

**Comment by st0012** [comment]
@NaturalHokke thanks for reporting this. this looks like an issue on the Ruby itself tbh. are you able to reproduce the issue consistently?

**Comment by NaturalHokke** [comment]
There was no way to reproduce it, and it seems that it was a problem of Ruby itself.
