### ISSUE TITLE
Race condition in Sentry::Net::HTTP?

### ISSUE THREAD

**Issue by schmijos** [getsentry/sentry-ruby#1492]
**Describe the bug**

There are two different `ActiveJob` jobs run with `deliver_later` in concurrent-ruby. Both send an SMS via the `vonage` gem at approximately the same time. While the SMS both reach their targets, I get two errors about 6ms apart from each other:

```
2021-06-30T07:41:03.227498+00:00 app[web.1]: E, [2021-06-30T07:41:03.227387 #4] ERROR -- : [ActiveJob] [ConfirmationSmsSenderJob] [ef95085e-fd26-42f2-8974-765756065eed] Error performing ConfirmationSmsSenderJob (Job ID: ef95085e-fd26-42f2-8974-765756065eed) from Async(default) in 456.12ms: IOError (stream closed in another thread):
2021-06-30T07:41:03.227535+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:217:in `wait_readable'
2021-06-30T07:41:03.227536+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:217:in `rbuf_fill'
2021-06-30T07:41:03.227536+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
2021-06-30T07:41:03.227537+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
2021-06-30T07:41:03.227537+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
2021-06-30T07:41:03.227537+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
2021-06-30T07:41:03.227538+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
2021-06-30T07:41:03.227538+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
2021-06-30T07:41:03.227538+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
2021-06-30T07:41:03.227539+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1492:in `request'
2021-06-30T07:41:03.227540+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/net/http.rb:38:in `request'
2021-06-30T07:41:03.227540+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
2021-06-30T07:41:03.227540+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:933:in `start'
2021-06-30T07:41:03.227541+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1483:in `request'
2021-06-30T07:41:03.227541+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/net/http.rb:38:in `request'
2021-06-30T07:41:03.227541+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/vonage-7.2.1/lib/vonage/namespace.rb:84:in `request'
2021-06-30T07:41:03.227541+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/vonage-7.2.1/lib/vonage/sms.rb:105:in `send'
2021-06-30T07:41:03.227547+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.6451/lib/types/private/methods/call_validation_2_7.rb:703:in `bind_call'
2021-06-30T07:41:03.227549+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.6451/lib/types/private/methods/call_validation_2_7.rb:703:in `block in create_validator_method_medium1'
2021-06-30T07:41:03.227549+00:00 app[web.1]: /app/app/services/vonage_service.rb:31:in `send_sms'
2021-06-30T07:41:03.227550+00:00 app[web.1]: /app/app/jobs/confirmation_sms_sender_job.rb:9:in `block in perform'
2021-06-30T07:41:03.227550+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
2021-06-30T07:41:03.227550+00:00 app[web.1]: /app/app/jobs/confirmation_sms_sender_job.rb:6:in `perform'
2021-06-30T07:41:03.227550+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:48:in `block in perform_now'
2021-06-30T07:41:03.227550+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
2021-06-30T07:41:03.227551+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-rails-4.5.1/lib/sentry/rails/active_job.rb:28:in `capture_and_reraise_with_sentry'
2021-06-30T07:41:03.227551+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-rails-4.5.1/lib/sentry/rails/active_job.rb:12:in `block (3 levels) in included'
2021-06-30T07:41:03.227551+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/hub.rb:56:in `with_scope'
2021-06-30T07:41:03.227551+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry-ruby.rb:167:in `with_scope'
2021-06-30T07:41:03.227552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-rails-4.5.1/lib/sentry/rails/active_job.rb:11:in `block (2 levels) in included'
2021-06-30T07:41:03.227552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.227552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.227552+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
2021-06-30T07:41:03.227553+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
2021-06-30T07:41:03.227553+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.227553+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.227554+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
2021-06-30T07:41:03.227554+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
2021-06-30T07:41:03.227554+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.227560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.227560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:21:in `block in instrument'
2021-06-30T07:41:03.227560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
2021-06-30T07:41:03.227560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2021-06-30T07:41:03.227560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
2021-06-30T07:41:03.227560+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:31:in `instrument'
2021-06-30T07:41:03.227561+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
2021-06-30T07:41:03.227561+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.227561+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.227561+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:22:in `block in tag_logger'
2021-06-30T07:41:03.227562+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
2021-06-30T07:41:03.227562+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
2021-06-30T07:41:03.227562+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
2021-06-30T07:41:03.227562+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:22:in `tag_logger'
2021-06-30T07:41:03.227563+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
2021-06-30T07:41:03.227563+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.227563+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.227563+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
2021-06-30T07:41:03.227568+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:47:in `perform_now'
2021-06-30T07:41:03.227569+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:25:in `block in execute'
2021-06-30T07:41:03.227569+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
2021-06-30T07:41:03.227569+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
2021-06-30T07:41:03.227569+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-06-30T07:41:03.227570+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
2021-06-30T07:41:03.227570+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-06-30T07:41:03.227570+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:71:in `wrap'
2021-06-30T07:41:03.227570+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
2021-06-30T07:41:03.227570+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.227571+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.227571+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
2021-06-30T07:41:03.227571+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:23:in `execute'
2021-06-30T07:41:03.227571+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
2021-06-30T07:41:03.227572+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
2021-06-30T07:41:03.227572+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
2021-06-30T07:41:03.227575+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
2021-06-30T07:41:03.227576+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
2021-06-30T07:41:03.227576+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
2021-06-30T07:41:03.227576+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
```

```
2021-06-30T07:41:03.234193+00:00 app[web.1]: E, [2021-06-30T07:41:03.233389 #4] ERROR -- : [ActiveJob] [VendorBookingNotificationJob] [86146c5a-a5d6-43d0-be85-4169e476d17f] Error performing VendorBookingNotificationJob (Job ID: 86146c5a-a5d6-43d0-be85-4169e476d17f) from Async(default) in 456.23ms: EOFError (end of file reached):
2021-06-30T07:41:03.234194+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill'
2021-06-30T07:41:03.234194+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/protocol.rb:159:in `read'
2021-06-30T07:41:03.234195+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:330:in `ensure in read_chunked'
2021-06-30T07:41:03.234195+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:330:in `read_chunked'
2021-06-30T07:41:03.234195+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:291:in `block in read_body_0'
2021-06-30T07:41:03.234196+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:284:in `inflater'
2021-06-30T07:41:03.234196+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:289:in `read_body_0'
2021-06-30T07:41:03.234196+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:210:in `read_body'
2021-06-30T07:41:03.234197+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:235:in `body'
2021-06-30T07:41:03.234197+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http/response.rb:168:in `reading_body'
2021-06-30T07:41:03.234197+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1536:in `transport_request'
2021-06-30T07:41:03.234197+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1492:in `request'
2021-06-30T07:41:03.234198+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/net/http.rb:38:in `request'
2021-06-30T07:41:03.234198+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1485:in `block in request'
2021-06-30T07:41:03.234198+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:933:in `start'
2021-06-30T07:41:03.234198+00:00 app[web.1]: /app/vendor/ruby-2.7.1/lib/ruby/2.7.0/net/http.rb:1483:in `request'
2021-06-30T07:41:03.234199+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/net/http.rb:38:in `request'
2021-06-30T07:41:03.234199+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/vonage-7.2.1/lib/vonage/namespace.rb:84:in `request'
2021-06-30T07:41:03.234199+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/vonage-7.2.1/lib/vonage/sms.rb:105:in `send'
2021-06-30T07:41:03.234199+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.6451/lib/types/private/methods/call_validation_2_7.rb:703:in `bind_call'
2021-06-30T07:41:03.234200+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sorbet-runtime-0.5.6451/lib/types/private/methods/call_validation_2_7.rb:703:in `block in create_validator_method_medium1'
2021-06-30T07:41:03.234200+00:00 app[web.1]: /app/app/services/vonage_service.rb:31:in `send_sms'
2021-06-30T07:41:03.234200+00:00 app[web.1]: /app/app/jobs/vendor_booking_notification_job.rb:8:in `block in perform'
2021-06-30T07:41:03.234200+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
2021-06-30T07:41:03.234201+00:00 app[web.1]: /app/app/jobs/vendor_booking_notification_job.rb:7:in `perform'
2021-06-30T07:41:03.234201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:48:in `block in perform_now'
2021-06-30T07:41:03.234201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
2021-06-30T07:41:03.234201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-rails-4.5.1/lib/sentry/rails/active_job.rb:28:in `capture_and_reraise_with_sentry'
2021-06-30T07:41:03.234201+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-rails-4.5.1/lib/sentry/rails/active_job.rb:12:in `block (3 levels) in included'
2021-06-30T07:41:03.234202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/hub.rb:56:in `with_scope'
2021-06-30T07:41:03.234202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry-ruby.rb:167:in `with_scope'
2021-06-30T07:41:03.234202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-rails-4.5.1/lib/sentry/rails/active_job.rb:11:in `block (2 levels) in included'
2021-06-30T07:41:03.234202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.234202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.234202+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/i18n-1.8.10/lib/i18n.rb:314:in `with_locale'
2021-06-30T07:41:03.234203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
2021-06-30T07:41:03.234203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.234203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.234203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
2021-06-30T07:41:03.234203+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
2021-06-30T07:41:03.234207+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.234208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.234208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:21:in `block in instrument'
2021-06-30T07:41:03.234208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
2021-06-30T07:41:03.234208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
2021-06-30T07:41:03.234208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
2021-06-30T07:41:03.234208+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:31:in `instrument'
2021-06-30T07:41:03.234209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
2021-06-30T07:41:03.234209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.234209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.234209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:22:in `block in tag_logger'
2021-06-30T07:41:03.234209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
2021-06-30T07:41:03.234209+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:37:in `tagged'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/tagged_logging.rb:99:in `tagged'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:22:in `tag_logger'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
2021-06-30T07:41:03.234210+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:47:in `perform_now'
2021-06-30T07:41:03.234211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:25:in `block in execute'
2021-06-30T07:41:03.234211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
2021-06-30T07:41:03.234211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
2021-06-30T07:41:03.234211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-06-30T07:41:03.234211+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
2021-06-30T07:41:03.234212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
2021-06-30T07:41:03.234212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/reloader.rb:71:in `wrap'
2021-06-30T07:41:03.234212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
2021-06-30T07:41:03.234212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `instance_exec'
2021-06-30T07:41:03.234212+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
2021-06-30T07:41:03.234213+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/callbacks.rb:137:in `run_callbacks'
2021-06-30T07:41:03.234213+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/execution.rb:23:in `execute'
2021-06-30T07:41:03.234213+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/activejob-6.1.3.2/lib/active_job/queue_adapters/async_adapter.rb:70:in `perform'
2021-06-30T07:41:03.234214+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
2021-06-30T07:41:03.234214+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
2021-06-30T07:41:03.234217+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
2021-06-30T07:41:03.234217+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
2021-06-30T07:41:03.234217+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
2021-06-30T07:41:03.234218+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/concurrent-ruby-1.1.9/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
```

**To Reproduce**

Only happens in production from time to time. This is how I suspect that it's a problem of `sentry-ruby` (which I only include in production).

**Environment**
 - Ruby Version: 2.7.1p83
 - SDK Version: 4.5.1
 - Integration Versions: Rails 6.1.3.2 with concurrent-ruby 1.1.9

**Raven Config**

This is not necessary but could be helpful.

```ruby
# config/initializers/sentry.rb

if defined? Sentry
  Sentry.init do |config|
    config.dsn = ENV['SENTRY_DSN']
    config.breadcrumbs_logger = [:active_support_logger]
  end
end
```

**Comment by st0012** [comment]
@schmijos I don't think this is caused by the SDK. the code only collects information from req/res objects and add it to the scope. it doesn't make any connection itself.


you can also see that the line backtrace points to (`38`) is just `super` for calling the original implementation.

```
2021-06-30T07:41:03.227540+00:00 app[web.1]: /app/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-4.5.1/lib/sentry/net/http.rb:38:in `request'
```

https://github.com/getsentry/sentry-ruby/blob/c80f37ea45d103259a862ffb0a4a5515d313fcdc/sentry-ruby/lib/sentry/net/http.rb#L35-L42

**Comment by schmijos** [comment]
I worked around the problem setting up _sidekiq_. No idea, what the original problem was.
