### ISSUE TITLE
Stack Level Too Deep: Heroku, sentry-resque with sentry-ruby, unusable

### ISSUE THREAD

**Issue by bmo** [getsentry/sentry-ruby#1496]
** Problem **
sentry-ruby with sentry-rails and sentry-resque is not usable on Heroku. We cannot reproduce this when run locally. We note others have had this issue, with the response being "filter your objects"  - #1266; I'd like to separate that concern into one that Sentry deals with, not us.

in the Gemfile, have
```
gem "sentry-ruby", '~> 4.6.0'
gem "sentry-rails"
gem "sentry-resque"
```
When we catch an exception, this happens (we set up a mailer to throw an exception specifically to troubleshoot this):
```
2021-07-02T22:50:36.123624+00:00 app[resque.1]: D, [2021-07-02T22:50:36.123501 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.124928+00:00 app[resque.1]: D, [2021-07-02T22:50:36.124884 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.125262+00:00 app[resque.1]: D, [2021-07-02T22:50:36.125229 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.125634+00:00 app[resque.1]: D, [2021-07-02T22:50:36.125602 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.125830+00:00 app[resque.1]: D, [2021-07-02T22:50:36.125798 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.126127+00:00 app[resque.1]: D, [2021-07-02T22:50:36.126093 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.126350+00:00 app[resque.1]: D, [2021-07-02T22:50:36.126319 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.126595+00:00 app[resque.1]: D, [2021-07-02T22:50:36.126533 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.126811+00:00 app[resque.1]: D, [2021-07-02T22:50:36.126776 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.127064+00:00 app[resque.1]: D, [2021-07-02T22:50:36.127033 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:36.127294+00:00 app[resque.1]: D, [2021-07-02T22:50:36.127265 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
```
< Omitting 100s or 1000s of additional lines >
Then:
```
2021-07-02T22:50:36.973063+00:00 app[resque.1]: D, [2021-07-02T22:50:36.973040 #32] DEBUG -- sentry: [Tracing] Starting <resque> transaction <ActionMailer::MailDeliveryJob>
2021-07-02T22:50:40.085443+00:00 app[resque.1]: I, [2021-07-02T22:50:40.085351 #32]  INFO -- sentry: Sending envelope [event] 8e87328a0c3e48d1b7116d171a36bedd to Sentry
2021-07-02T22:50:42.022280+00:00 app[resque.1]: I, [2021-07-02T22:50:42.022190 #32]  INFO -- sentry: Sending envelope [event] afedcc236e9d461ea501b59ba6e02335 to Sentry
2021-07-02T22:50:42.504092+00:00 heroku[resque.1]: Process running mem=532M(103.9%)
2021-07-02T22:50:42.505694+00:00 heroku[resque.1]: Error R14 (Memory quota exceeded)
2021-07-02T22:50:43.496833+00:00 app[resque.1]: I, [2021-07-02T22:50:43.496743 #32]  INFO -- sentry: Sending envelope [event] 91341e45dbd144d9bb5a7a06ca240eae to Sentry
2021-07-02T22:50:45.618702+00:00 app[resque.1]: I, [2021-07-02T22:50:45.618602 #32]  INFO -- sentry: Sending envelope [event] 31cadbf3eb0f4f11b7e32075aa7253c4 to Sentry
2021-07-02T22:50:47.439242+00:00 app[resque.1]: I, [2021-07-02T22:50:47.439153 #32]  INFO -- sentry: Sending envelope [event] c9cffc25a3b246c1a9b7a0d2b06fa77f to Sentry
2021-07-02T22:50:49.547215+00:00 app[resque.1]: I, [2021-07-02T22:50:49.547115 #32]  INFO -- sentry: Sending envelope [event] fad8bc54a4cf4bbba28238b9594705f8 to Sentry
2021-07-02T22:50:51.601746+00:00 app[resque.1]: I, [2021-07-02T22:50:51.601633 #32]  INFO -- sentry: Sending envelope [event] c269c4aea18d4a3abf5def0fb66ebb44 to Sentry
2021-07-02T22:50:51.668430+00:00 app[resque.1]: E, [2021-07-02T22:50:51.668348 #32] ERROR -- sentry: Event sending failed: the server responded with status 413
2021-07-02T22:50:51.668430+00:00 app[resque.1]: body: {"detail":"failed to read request body","causes":["payload reached its size limit"]}
2021-07-02T22:50:51.724024+00:00 app[resque.1]: I, [2021-07-02T22:50:51.723942 #32]  INFO -- sentry: Unreported Event: SystemStackError: stack level too deep
2021-07-02T22:50:51.739826+00:00 app[resque.1]: E, [2021-07-02T22:50:51.739748 #32] ERROR -- sentry: Event capturing failed: the server responded with status 413
2021-07-02T22:50:51.739827+00:00 app[resque.1]: body: {"detail":"failed to read request body","causes":["payload reached its size limit"]}
```

**Expected behavior**
Exceptions are reported, resque processing continues on.

**Actual behavior**
Exceptions are NOT reported; resque processing instance runs out of memory, is unusable, jobs stop. Sadness ensues.

**Environment**
 - Ruby Version: 2.7.3
 - SDK Version: sentry-rails (4.6.0), sentry-resque (4.6.0)
 - Integration Versions (if any):
  - Rails 6.1.4 , Resque 2.0.0

**Sentry Config**

```ruby
Sentry.init do |config|
  # the config you're using, without DSN and other sensitive data
  config.breadcrumbs_logger = [:sentry_logger]
  config.traces_sample_rate = 0.5
  config.traces_sampler = lambda do |context|
      true
  end
  config.send_default_pii = true
end
```

**Comment by st0012** [comment]
@bmo thanks for reporting the issue.
are you saying the SDK causes `SystemStackError`, or you're trying to catch `SystemStackError` but `sentry-resque` ran out of memory?
from the title, it looks like the former. but from the log, it looks like the latter

```
# this means the SDK failed to report an event of `SystemStackError` because it exceeded size limit
Event sending failed: the server responded with status 413
2021-07-02T22:50:51.668430+00:00 app[resque.1]: body: {"detail":"failed to read request body","causes":["payload reached its size limit"]}
Unreported Event: SystemStackError: stack level too deep
```

if the `SystemStackError` is caused by the SDK, can you provide me its backtrace?

### Other Notes

this doesn't relate to the issue: `traces_sample_rate` and `traces_sampler` should not both be set. in this case, it ignores `traces_sample_rate`.

**Comment by bmo** [comment]
Greetings; the SystemStackError on our Resque background processing instance seems to be caused by the combination of Heroku AND sentry-resque. Using sentry-resque on local development machines handling Resque (and everything else) does not blow the stack.  Our test setup does the following:
```
class GeneralIntegrityJob < ApplicationJob
   queue_as GeneralIntegrityJob.queue
 
   def perform
     raise StandardError.new("An error in GeneralIntegrityJob generated on purpose #{SecureRandom.random_number(10**36).to_s(16)}") 
     # ... rest of method omitted
   end
   # rest of file omitted
end
```

We trigger the problem by triggering the job from another instance in the infrastructure

**Comment by samsonjs** [comment]
We ran into a similar issue with Scout APM. It looks like they have some similar reports too: https://github.com/scoutapp/scout_apm_ruby/issues/309

Here's our stack trace for reference:

```
[07/06/21 18:04:11 +0000 worker-f1cd15d4f808 (18)] INFO : Exception sending request to server: 
stack level too deep
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/config.rb:226:in `each'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/config.rb:226:in `detect'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/config.rb:226:in `overlay_for_key'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/config.rb:234:in `value'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:43:in `request_scout_description'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
	/usr/local/bundle/gems/sentry-ruby-core-4.6.0/lib/sentry/net/http.rb:38:in `request'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:34:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:44:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
	/usr/local/bundle/gems/sentry-ruby-core-4.6.0/lib/sentry/net/http.rb:38:in `request'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:34:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:44:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
	/usr/local/bundle/gems/sentry-ruby-core-4.6.0/lib/sentry/net/http.rb:38:in `request'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:34:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:44:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:29:in `request_with_scout_instruments'
	/usr/local/bundle/gems/sentry-ruby-core-4.6.0/lib/sentry/net/http.rb:38:in `request'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/instruments/net_http.rb:30:in `block in request_with_scout_instruments'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:34:in `instrument'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:44:in `instrument'
[... thousands of lines...]
	/usr/local/bundle/gems/sentry-ruby-core-4.6.0/lib/sentry/net/http.rb:38:in `request'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:85:in `block in post'
	/usr/local/lib/ruby/3.0.0/net/http.rb:960:in `start'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:92:in `request'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:80:in `post'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:158:in `block in post_payload'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:156:in `each'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:156:in `post_payload'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporter.rb:40:in `report'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporting.rb:93:in `deliver_period'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporting.rb:52:in `block in report_to_server'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/layaway.rb:103:in `with_claim'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporting.rb:45:in `report_to_server'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/reporting.rb:36:in `process_metrics'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/periodic_work.rb:13:in `run'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/agent.rb:178:in `block (2 levels) in start_background_worker'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/background_worker.rb:61:in `block in start'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/background_worker.rb:44:in `loop'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/background_worker.rb:44:in `start'
	/usr/local/bundle/gems/scout_apm-4.0.4/lib/scout_apm/agent.rb:177:in `block in start_background_worker'
[07/06/21 18:22:11 +0000 worker-f1cd15d4f808 (18)] WARN : Error on checkin to https://checkin.scoutapp.com/apps/checkin.scout?key=redacted&name=redacted: :connection_failed
[2021-07-06 18:22:25.694] ERROR -- stack level too deep: nil
```

**Comment by marclafratta** [comment]
We had the same issue using sidekiq & redis elasticache on aws. Fills redis immediately on startup, then sidekiq runners start to fall over.

**Comment by st0012** [comment]
@samsonjs thanks for providing stacktrace 🙂 
@marclafratta @bmo does your application's backtrace look similar to what @samsonjs posted?
if it is, the problem is a conflict between how this SDK and other gems (like Scout APM's SDK) patches the `Net::HTTP` library, which is described in https://github.com/getsentry/sentry-ruby/issues/1427. this should also explain why it only happens on production.

**Comment by rusucosmin** [comment]
+1
