### ISSUE TITLE
Sentry Sidekiq JSON Serialisation Exception Severity:HIGH

### ISSUE THREAD

**Issue by itay-grudev** [getsentry/sentry-ruby#1785]
### Issue Description

Upon serializing a job for Sidekiq the following exception get's thrown, by `sentry-sidekiq` preventing the job from being sent to Redis. The request crashes, the user gets `500` and what's worse is that no error job gets sent to Sentry, so this was a massive pain to acquire.

Below is the stack trace of the failure starting with a call to `deliver_later` for a new user registration. As to the weird symbols, those come from attempting to serialize the encrypted contents of `Rails::Credentials`. I certainly don't plan to provide examples.

```ruby
exception: Encoding::UndefinedConversionError",
exception_message: "\"\\xFD\" from ASCII-8BIT to UTF-8",
```

```text
/home/app/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:312:in `generate',
/home/app/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:312:in `generate',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq.rb:187:in `dump_json',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:210:in `block in atomic_push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:208:in `map',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:208:in `atomic_push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:193:in `block (2 levels) in raw_push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:2670:in `block in pipelined',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize',
/home/app/.rbenv/versions/3.0.2/lib/ruby/3.0.0/monitor.rb:202:in `synchronize',
/home/app/.rbenv/versions/3.0.2/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/redis-4.5.1/lib/redis.rb:2667:in `pipelined',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:192:in `block in raw_push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:191:in `raw_push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:77:in `push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sidekiq-6.4.0/lib/sidekiq/client.rb:140:in `push',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/queue_adapters/sidekiq_adapter.rb:22:in `enqueue',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/enqueuing.rb:59:in `block in enqueue',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/instrumentation.rb:21:in `block in instrument',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/notifications.rb:203:in `block in instrument',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sentry-rails-5.2.1/lib/sentry/rails/tracing.rb:54:in `instrument',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/notifications.rb:203:in `instrument',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/instrumentation.rb:31:in `instrument',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/instrumentation.rb:9:in `block (2 levels) in \u003cmodule:Instrumentation\u003e',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:126:in `instance_exec',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/logging.rb:22:in `block in tag_logger',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/tagged_logging.rb:99:in `block in tagged',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/tagged_logging.rb:37:in `tagged',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/tagged_logging.rb:99:in `tagged',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/logging.rb:22:in `tag_logger',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/logging.rb:14:in `block (2 levels) in \u003cmodule:Logging\u003e',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:126:in `instance_exec',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:137:in `run_callbacks',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/enqueuing.rb:55:in `enqueue',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/activejob-6.1.4.7/lib/active_job/configured_job.rb:16:in `perform_later',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.4.7/lib/action_mailer/message_delivery.rb:146:in `enqueue_delivery',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/actionmailer-6.1.4.7/lib/action_mailer/message_delivery.rb:99:in `deliver_later',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/devise-async-1.0.0/lib/devise/async/model.rb:53:in `deliver_mail_later',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/devise-async-1.0.0/lib/devise/async/model.rb:33:in `send_devise_notification',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/devise-5d5636f03ac1/lib/devise/models/confirmable.rb:121:in `send_confirmation_instructions',
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/bundler/gems/devise-5d5636f03ac1/lib/devise/models/confirmable.rb:183:in `send_on_create_confirmation_instructions',
```

### Reproduction Steps

N/A

### Expected Behavior

No exception is thrown for invalid JSON characters or Rails Credentials are filtered from the serialization by default.

### Actual Behavior

An exception is thrown, causing the system to render a 500. Job is not dispatched to Sidekiq. No error is reported by Sentry.

### Ruby Version

3.0.2

### SDK Version

5.2.1

### Integration and Its Version

Rails + Ruby + Sidekiq

### Sentry Config

```ruby
# frozen_string_literal: true

##
# Sentry configuration
Sentry.init do |config|
  ##
  # Personally identifiable information (PII)
  config.send_default_pii = true

  # Use the Rails application parameter sanitization
  filter = ActiveSupport::ParameterFilter.new( Rails.application.config.filter_parameters )
  config.before_send = lambda do |event, hint|
    filter.filter( event.to_hash )
  end

  ##
  # Breadcrumb logger is used to supply additional information to Sentry
  config.breadcrumbs_logger = %i[ active_support_logger ]

  ##
  # Performance monitoring
  # config.traces_sample_rate = 1

  ##
  # Asynchronous reporting to Sentry
  config.async = lambda do |event, hint|
    Sentry::SendEventJob.perform_later( event, hint )
  end
end
```

**Comment by itay-grudev** [comment]
We solved the issue by downgrading to version `4.4.0` which we were using previously.

**Comment by sl0thentr0py** [comment]
but the exception is in sidekiq when it tried to queue the job? I don't see any `sentry-sidekiq` in your stacktrace.

**Comment by itay-grudev** [comment]
You may be correct. But I believe the problem starts from this point in the stack trace:

```txt
/home/app/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/sentry-rails-5.2.1/lib/sentry/rails/tracing.rb:54:in `instrument',
```

**Comment by sl0thentr0py** [comment]
That's just an instrumentation wrapper that yields to the block given eventually.
I don't think this is a problem anywhere in sentry, this is a serialization problem in sidekiq. 
If you still think this is a sentry problem, you need to give me some sort of minimal reproduction case.

**Comment by itay-grudev** [comment]
Will look into it again. Thank you for your time.
