### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by RanX12** [getsentry/sentry-ruby#1872]
### Issue Description

```ruby
#<Thread:0x0000000001ddae18 /var/lib/jenkins/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
/var/lib/jenkins/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sshkit-1.21.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as domain: rake exit status: 1 (SSHKit::Runner::ExecuteError)
rake stdout: Nothing written
rake stderr: [DEPRECATED] The option ignore_url_patterns is being removed. Consider using transaction_ignore_urls instead.
rake aborted!
SystemStackError: stack level too deep
/data/www/project/shared/bundle/ruby/2.7.0/gems/elastic-apm-3.10.1/lib/elastic_apm.rb:59:in `start'
/data/www/project/shared/bundle/ruby/2.7.0/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/rake.rb:30:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/sentry-ruby-5.4.2/lib/sentry/rake.rb:24:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/sentry-ruby-5.4.2/lib/sentry/rake.rb:24:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/sentry-ruby-5.4.2/lib/sentry/rake.rb:24:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/elastic-apm-3.10.1/lib/elastic_apm/spies/rake.rb:33:in `execute'
/data/www/project/shared/bundle/ruby/2.7.0/gems/sentry-ruby-5.4.2/lib/sentry/rake.rb:24:in `execute'
```

Not sure if it's a bug

### Reproduction Steps

Gemfile add
```ruby
# APM agent
gem 'elastic-apm'

# Sentry
gem "sentry-ruby"
gem "sentry-rails"
```

add config/elastic_apm.yml
```yml
# config/elastic_apm.yml:

service_name: '...'
secret_token: '...'
server_url: '...'
hostname: '...'

filter_exception_types:
  - 'AbstractController::ActionNotFound'
  - 'ActionController::RoutingError'
  - 'ActionController::UnknownHttpMethod'
```

add config/initializers/sentry.rb
```ruby
# frozen_string_literal: true

if Figaro.env.RAILS_SENTRY.present?
  Sentry.init do |config|
    config.dsn = Figaro.env.RAILS_SENTRY
    config.breadcrumbs_logger = [:active_support_logger, :http_logger]
    config.environment = Figaro.env.SENTRY_ENV

    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production.
    config.traces_sample_rate = 1.0
  end
end
```

### Expected Behavior

run `bin/cap develop deploy` Should be deployed successfully, But it is wrong`SystemStackError: stack level too deep`

### Actual Behavior

SystemStackError: stack level too deep

### Ruby Version

2.7.0

### SDK Version

5.4.2

**Comment by st0012** [comment]
This is caused by the same reason I mentioned [here](https://github.com/getsentry/sentry-ruby/issues/1873#issuecomment-1235923902). But in your case, `elasic-apm` actually already [fixed it after v4.0.0](https://github.com/elastic/apm-agent-ruby/commit/636319cdcdfe517757e397ba053b63cdb9ebb600). So you can fix it by upgrading it.
