### ISSUE TITLE
SystemStackError: stack level too deep (rake Task#execute redefinition conflicts with capistrano airbrush)

### ISSUE THREAD

**Issue by borlafdev** [getsentry/sentry-ruby#1873]
### Issue Description

Possible duplicate of #1872 , but not sure.

Seems like the redefinition made by sentry gem of the Task#execute method conflicts with another redefinition made by capistrano's airbrush gem, causing infinite recursion...

Tried also loading the gem via GitHub, but no luck.

If any more info is needed, i'd be happy to help.

### Reproduction Steps

bundle exec cap STAGE deploy

### Expected Behavior

Normal deploy without issues

### Actual Behavior

```
warning: parser/current is loading parser/ruby25, which recognizes
warning: 2.5.3-compliant syntax, but you are running 2.5.8.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
** Invoke watcher-test (first_time)
** Execute watcher-test
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
cap aborted!
/home/bdev/.rvm/gems/ruby-2.5.8/gems/sentry-ruby-5.4.1/lib/sentry-ruby.rb:246:in `initialized?'
SystemStackError: stack level too deep
# These two lines are repeated 10k times, but cannot show all due to github body limit
/home/bdev/.rvm/gems/ruby-2.5.8/gems/sentry-ruby-5.4.1/lib/sentry/rake.rb:24:in `execute'
/home/bdev/.rvm/gems/ruby-2.5.8/gems/airbrussh-1.3.1/lib/airbrussh/rake/context.rb:62:in `execute'
# end of repeated lines
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/home/bdev/.rvm/gems/ruby-2.5.8/gems/capistrano-3.11.0/lib/capistrano/dsl/task_enhancements.rb:16:in `block in after'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/home/bdev/.rvm/gems/ruby-2.5.8/gems/sentry-ruby-5.4.1/lib/sentry/rake.rb:24:in `execute'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/monitor.rb:235:in `mon_synchronize'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/home/bdev/.rvm/rubies/ruby-2.5.8/lib/ruby/gems/2.5.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/home/bdev/.rvm/gems/ruby-2.5.8/gems/capistrano-3.11.0/lib/capistrano/application.rb:14:in `run'
/home/bdev/.rvm/gems/ruby-2.5.8/gems/capistrano-3.11.0/bin/cap:3:in `<top (required)>'
/home/bdev/.rvm/gems/ruby-2.5.8/bin/cap:25:in `load'
/home/bdev/.rvm/gems/ruby-2.5.8/bin/cap:25:in `<main>'
/home/bdev/.rvm/gems/ruby-2.5.8/bin/ruby_executable_hooks:22:in `eval'
/home/bdev/.rvm/gems/ruby-2.5.8/bin/ruby_executable_hooks:22:in `<main>'
Tasks: TOP => rvm:hook
```

### Ruby Version

2.5.8

### SDK Version

sentry-rails (5.3.1) sentry-ruby (5.4.1) sentry-ruby-core (5.3.1)

### Integration and Its Version

capistrano (3.11.0)

### Sentry Config

```ruby
  Sentry.init do |config|
    config.dsn             = ENV['SENTRY_DSN']
    config.enabled_environments    = ['development', 'production']
    config.breadcrumbs_logger = [:sentry_logger, :monotonic_active_support_logger, :active_support_logger, :http_logger]
    config.logger = Logger.new('log/sentry.log')

    # Set tracesSampleRate to 1.0 to capture 100%
    # of transactions for performance monitoring.
    # We recommend adjusting this value in production
    config.traces_sample_rate = 1.0
    config.debug = true
    # or
    config.traces_sampler = lambda do |context|
      true
    end
  end
```

**Comment by st0012** [comment]
It's because `airbrussh` uses [alias_method](https://github.com/mattbrictson/airbrussh/blob/d440931db4f593fd0dbf14e310d6173f9b6973d3/lib/airbrussh/rake/context.rb#L58) to patch the method, which is known to conflict with the `prepend` approach we're using. And since the community consensus is to move away from `alias_method` to `prepend`, I recommend you to open an issue there.
