### ISSUE TITLE
undefined method `arity`

### ISSUE THREAD

**Issue by mbajur** [getsentry/sentry-ruby#2122]
### Issue Description

I recently upgraded my rails app to ruby 3.2.2 and Sidekiq 7.1.5 and that's what is being raised when sidekiq tries to run a job:

```
NoMethodError: undefined method `new' for Sidekiq::Job:Module
!!! ERROR HANDLER THREW AN ERROR !!!
#<NoMethodError: undefined method `arity' for #<Sentry::Sidekiq::ErrorHandler:0x00007f78c5350d28>>
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:267:in `block in handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `each'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:193:in `rescue in block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:177:in `block in process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:176:in `process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:82:in `process_one'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:72:in `run'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:10:in `watchdog'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:19:in `block in safe_thread'
/usr/local/bundle/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:435:in `block (2 levels) in thread_block_with_current_transaction'
/usr/local/bundle/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/usr/local/bundle/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:434:in `block in thread_block_with_current_transaction'
#<NoMethodError: undefined method `arity' for #<Sentry::Sidekiq::ErrorHandler:0x00007f78c5350d28>>
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:267:in `block in handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `each'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/config.rb:266:in `handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:48:in `handle_exception'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:193:in `rescue in block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:178:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:177:in `handle_interrupt'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:177:in `block in process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:176:in `handle_interrupt'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:176:in `process'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:82:in `process_one'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/processor.rb:72:in `run'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:10:in `watchdog'
/usr/local/bundle/gems/sidekiq-7.1.5/lib/sidekiq/component.rb:19:in `block in safe_thread'
/usr/local/bundle/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:435:in `block (2 levels) in thread_block_with_current_transaction'
/usr/local/bundle/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:357:in `capture_segment_error'
/usr/local/bundle/gems/newrelic_rpm-9.5.0/lib/new_relic/agent/tracer.rb:434:in `block in thread_block_with_current_transaction'
```

### Reproduction Steps

Does not apply

### Expected Behavior

No exception being raised

### Actual Behavior

Exception being raised

### Ruby Version

3.2.2

### SDK Version

5.11.0

### Integration and Its Version

Rails 7.0.8

### Sentry Config

```
# frozen_string_literal: true

Sentry.init do |config|
  config.dsn = Figaro.env.sentry_dsn
  config.breadcrumbs_logger = [:active_support_logger]
  config.traces_sample_rate = 0

  config.release = "myapp@v#{MyApp::Version::VERSION}" if Figaro.env.forward_version_to_sentry
end
```

**Comment by sl0thentr0py** [comment]
this is fixed upstream in https://github.com/sidekiq/sidekiq/issues/6065
will just wait for that to be released, not on our side.

**Comment by sl0thentr0py** [comment]
7.1.6 is released
