### ISSUE TITLE
scrub!': can't modify frozen String (RuntimeError)

### ISSUE THREAD

**Issue by thde** [getsentry/sentry-ruby#821]
Hey, I just stumbled over this exception which should been fixed since 2.7.0 (https://github.com/getsentry/raven-ruby/issues/757):

````
vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:42:in `scrub!': can't modify frozen String (RuntimeError)
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:42:in `remove_invalid_bytes'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:30:in `process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `block in process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `merge!'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `block in process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `merge!'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `block in process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `merge!'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/processor/utf8conversion.rb:12:in `process'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/client.rb:63:in `block in encode'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/client.rb:63:in `each'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/client.rb:63:in `reduce'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/client.rb:63:in `encode'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/client.rb:34:in `send_event'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/instance.rb:81:in `send_event'
        from ... /vendor/bundle/ruby/2.3.0/gems/sentry-raven-2.7.1/lib/raven/instance.rb:126:in `capture_type'
       from /usr/lib/ruby/2.3.0/forwardable.rb:204:in `capture_exception'
````

It seems that the exception can still occur if the following two `if` statements return `false`:

https://github.com/getsentry/raven-ruby/blob/a365e13b5f1e948dd3702b1caa651d41e7d4aabd/lib/raven/processor/utf8conversion.rb#L25

https://github.com/getsentry/raven-ruby/blob/a365e13b5f1e948dd3702b1caa651d41e7d4aabd/lib/raven/processor/utf8conversion.rb#L29

**Comment by nateberkopec** [comment]
Thanks for the report, should be an easy fix.

**Comment by st0012** [comment]
closing because processors concept are removed from the new SDK
